/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'MW-RAJIB' at '9/16/16 4:07 PM' with Gradle 2.14
 *
 * @author MW-RAJIB, @date 9/16/16 4:07 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
